import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const uberMove = Inter({
  variable: "--font-uber-move",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${uberMove.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
