import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const appFont = Poppins({
  variable: "--font-app",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${appFont.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
